apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../v1.25

patches:
  - path: node-kubelet-path-patch.yaml
    target:
      group: apps
      version: v1
      kind: DaemonSet
      name: synology-csi-node
      namespace: synology-csi
