apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Uncomment and change to deploy into a custom namespace.
# This rewrites all namespace references in the rendered manifests.
# namespace: my-custom-csi-ns

resources:
  - ../v1.25

patches:
  - path: node-kubelet-path-patch.yaml
    target:
      group: apps
      version: v1
      kind: DaemonSet
      name: synology-csi-node
